import React from 'react'

import Head from 'next/head'
import { NavBar } from '../NavBar'

const MainLayouts = ({children}) => {
  return (
    <div>
      <Head>
        <title>Home </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavBar/>
  
      </div>
      <main >
        {children}
      </main>
    </div>
  )
}

export default MainLayouts
